server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/study_lab
        databaseName: study_lab
        username: affnet
        password: affnet
        testWhileIdle: true
        validationQuery: SELECT 1

    jpa:
        show_sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    redis:
        host: 127.0.0.1
        port: 6379
        timeout: 30
        maxTotal: 50
        minIdle: 10
        blockWhenExhausted: true
    broker:
        user: admin
        password: admin
