server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_SCHEMA}
        databaseName: ${MYSQL_SCHEMA}
        username: ${MYSQL_USER_NAME}
        password: ${MYSQL_PASSWORD}
        testWhileIdle: true
        validationQuery: SELECT 1
    jpa:
        show_sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    redis:
        host: ${REDIS_HOST}
        port: ${REDIS_PORT}
        timeout: 30
        maxTotal: 50
        minIdle: 10
        blockWhenExhausted: true
    messagebroker:
        relayhost: ${MQ_HOST}
        user: ${MQ_USER_NAME}
        password: ${MQ_PASSWORD}
