server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://${MYSQL_HOST}:3306
        databaseName: study_lab
        username: root
        password: root
        testWhileIdle: true
        validationQuery: SELECT 1

    jpa:
        show_sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    redis:
        host: ${REDIS_HOST}
        port: 6379
        timeout: 30
        maxTotal: 50
        minIdle: 10
        blockWhenExhausted: true
    messagebroker:
        relayhost: ${ACTIVEMQ_HOST}
        user: admin
        password: admin
